
export const heroData = {
    heroPaqueteBasico: {
        title: "Paquetes",
        subtitle: "Básicos",
        backgroundImage: "/img/banner-paquetes-Mensuales.jpg",
    },
    heroPaqueteTuisty: {
        title: "Paquetes",
        subtitle: "Tuisty",
        backgroundImage: "/img/banner-paquetes-Mensuales.jpg",
    },
    heroPaqueteTrimestral: {
        title: "Paqutes",
        subtitle: "Tuisty",
        paragraph: "Trimestrales",
        backgroundImage: "/img/banner-trimestrales.jpg",
    },
    heroPaqueteSemestral: {
      title: "Paqutes",
      subtitle: "Tuisty",
      paragraph: "Semestrales",
        backgroundImage: "/img/banner-semestrales.jpg",
    },
    heroPaqueteAnual: {
      title: "Paqutes",
      subtitle: "Tuisty",
      paragraph: "Anuales",
        backgroundImage: "/img/banner-anual.jpg",
    },
  }

export const planesData = {
    planesBasicosPage: {
      plans: [
        {
          name: "Tuisty 4GB + 3 días",
          data: "4GB",
          usage: "Navegación",
          price: "$39",
          minutes: "375",
          sms: "125",
          internet:"No",
          showSocialMedia: false,
          duration: "3 días",
          iftfolio: "1346921"
        },
        {
          name: "Tuisty 3GB + 7 días",
          data: "3GB",
          usage: "Navegación",
          price: "$59",
          minutes: "10,580",
          sms: "750",
          internet:"Si",
          showSocialMedia: true,
          socialMedia: [
            "facebook",
            "twitter",
            "whatsapp",
            "instagram",
            "snapchat",
            "telegram",
          ],
          duration: "7 días",
          iftfolio: "1346922"
        },
      ],
    },
    planesTuistyPage: {
        plans: [
            {
              name: "Tuisty 3",
              data: "3GB",
              usage: "Navegación",
              price: "$129",
              minutes: "44,700",
              sms: "1,500",
              internet:"Si",
              showSocialMedia: true,
              socialMedia: [
                "facebook",
                "twitter",
                "whatsapp",
                "instagram",
                "snapchat",
                "telegram",
              ],
              duration: "30 días",
              iftfolio: "1346925"
            },
            {
              name: "Tuisty 5",
              data: "5GB",
              usage: "Navegación",
              price: "$149",
              minutes: "44,700",
              sms: "1,500",
              internet:"Si",
              showSocialMedia: true,
              socialMedia: [
                "facebook",
                "twitter",
                "whatsapp",
                "instagram",
                "snapchat",
                "telegram",
              ],
              duration: "30 días",
              iftfolio: "1346926"
            },
            {
                name: "Tuisty 40",
                data: "40GB",
                usage: "Navegación",
                price: "$279",
                minutes: "44,700",
                sms: "1,500",
                internet:"Si",
                showSocialMedia: true,
                socialMedia: [
                  "facebook",
                  "twitter",
                  "whatsapp",
                  "instagram",
                  "snapchat",
                  "telegram",
                ],
                duration: "30 días",
                iftfolio: "1346929"
              },
              {
                name: "Tuisty 40+",
                data: "40GB",
                usage: "Navegación",
                price: "$349",
                minutes: "44,700",
                sms: "1,500",
                internet:"Si",
                showSocialMedia: true,
                socialMedia: [
                  "facebook",
                  "twitter",
                  "whatsapp",
                  "instagram",
                  "snapchat",
                  "telegram",
                ],
                duration: "30 días",
                iftfolio: "1346930"
              }
          ],
    },
    planesTrimestralesPage: {
      plans: [
          {
            name: "Tuisty 3",
            data: "3GB",
            usage: "Navegación",
            price: "$334",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "90 días",
            iftfolio: "0"
          },
          {
            name: "Tuisty 5",
            data: "5GB",
            usage: "Navegación",
            price: "$399",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "90 días",
            iftfolio: "1346936"
          },
          {
            name: "Tuisty 15",
            data: "15GB",
            usage: "Navegación",
            price: "$649",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "90 días",
            iftfolio: "1346938"
          },
          {
            name: "Tuisty 40",
            data: "40GB",
            usage: "Navegación",
            price: "$749",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "90 días",
            iftfolio: "1346941"
          },
        ],
    },
    planesSemestralesPage: {
      plans: [
          {
            name: "Tuisty 3",
            data: "3GB",
            usage: "Navegación",
            price: "$669",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "180 días",
            iftfolio: "0"
          },
          {
            name: "Tuisty 5",
            data: "5GB",
            usage: "Navegación",
            price: "$779",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "180 días",
            iftfolio: "1346946"
          },
          {
            name: "Tuisty 15",
            data: "15GB",
            usage: "Navegación",
            price: "$1299",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "180 días",
            iftfolio: "1346947"
          },
          {
            name: "Tuisty 40",
            data: "40GB",
            usage: "Navegación",
            price: "$1449",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "180 días",
            iftfolio: "1346949"
          },
        ],
    },
    planesAnualesPage: {
      plans: [
          {
            name: "Tuisty 3",
            data: "3GB",
            usage: "Navegación",
            price: "$1339",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "360 días",
            iftfolio: "0"
          },
          {
            name: "Tuisty 5",
            data: "5GB",
            usage: "Navegación",
            price: "$1599",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "360 días",
            iftfolio: "1346954"
          },
          {
            name: "Tuisty 15",
            data: "15GB",
            usage: "Navegación",
            price: "$2199",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "360 días",
            iftfolio: "1346956"
          },
          {
            name: "Tuisty 40",
            data: "40GB",
            usage: "Navegación",
            price: "$2669",
            minutes: "44,700",
            sms: "1,500",
            internet:"Si",
            showSocialMedia: true,
            socialMedia: [
              "facebook",
              "twitter",
              "whatsapp",
              "instagram",
              "snapchat",
              "telegram",
            ],
            duration: "360 días",
            iftfolio: "1346958"
          },
        ],
      },
  };
