
export const heroData = {
    heroPaqueteBasico: {
        title: "Tuisty",
        subtitle: "Básico",
        backgroundImage: "/img/banner-paquetes-Mensuales.jpg",
    },
    heroPaqueteTuisty: {
        title: "Tuisty",
        subtitle: "Mensual",
        backgroundImage: "/img/banner-paquetes-Mensuales.jpg",
    },
    heroLoginRegister: {
      title: "",
      subtitle: "Bienvenido",
      backgroundImage: "/",
    },
    heroPaqueteTrimestral: {
        title: "Tuisty",
        subtitle: "Trimestral",
        backgroundImage: "/img/banner-trimestrales.jpg",
    },
    heroPaqueteSemestral: {
      title: "Tuisty",
      subtitle: "Semestral",
        backgroundImage: "/img/banner-semestrales.jpg",
    },
    heroPaqueteAnual: {
      title: "Tuisty",
      subtitle: "Anual",
        backgroundImage: "/img/banner-anual.jpg",
    },
  }

export const planesData = {
  planesTuistyMainPage: {
    plans: [
        {
          id: 1,
          imgPlan: "/img/esencial-idea.png",
          dataPlan:"Plan",
          name: "Tuisty",
          dataType: "Semanal",
          data: "3GB",
          usage: "Navegación",
          price: 59,
          internet:"Si Comparte Internet",
          showSocialMedia: true,
          socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],
          showSocialMediaInter: true,
          socialMediaInter: [
            "whatsapp",
            "messenger",
            "telegram",
          ],
          duration: "7 días",
          iftfolio: "1640092"
        },
        {
          id: 2,
          imgPlan: "/img/esencial-idea.png",
          dataPlan:"Plan",
          name: "Tuisty",
          dataType: "Estándar",
          data: "6GB",
          usage: "Navegación",
          price: 129,
          internet:"Si Comparte Internet",
          showSocialMedia: true,
          socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],
          showSocialMediaInter: true,
          socialMediaInter: [
            "whatsapp",
            "messenger",
            "telegram",
          ],
          duration: "15 días",
          iftfolio: "1640110"
        },
        {
            id: 3,
            imgPlan: "/img/esencial-idea.png",
            dataPlan:"Plan",
            name: "Tuisty",
            dataType: "Escencial",
            data: "20GB",
            usage: "Navegación",
            price: 149,
            internet:"Si Comparte Internet",
            showSocialMedia: true,
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            showSocialMediaInter: true,
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "15 días",
            iftfolio: "1640123"
          },
          {
            id: 4,
            imgPlan: "/img/esencial-idea.png",
            dataPlan:"Plan",
            name: "Tuisty",
            dataType: "Prime",
            data: "40GB",
            usage: "Navegación",
            price: 229,
            internet:"Si Comparte Internet",
            showSocialMedia: true,
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            showSocialMediaInter: true,
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "30 días",
            iftfolio: "1644057"
          }
      ],
    },
    planesBasicosPage: {
      plans: [
        {
          id: 5,
          imgPlan: "/img/basicos.png",
          dataPlan:"Tuisty Básico",
          name: "Tuisty",
          dataPlus: "Básico",
          data: "4GB",
          usage: "Navegación",
          price: 39,
          llamadas:"375 min en llamadas y SMS a:",
          internet:"No Comparte Internet",
          socialText:"Sin Redes Sociales Nacionales Ilimitadas",
          /*socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],*/
          socialInterText:"Sin Redes Sociales Internacionales Ilimitadas",
          socialMediaInter: [
            /*"whatsapp",
            "messenger",
            "telegram",*/
          ],
          duration: "3 días",
          //durationPlus: "3 días",
          iftfolio: "1607762"
        },
        {
          id: 6,
          imgPlan: "/img/basicos.png",
          dataPlan:"Tuisty Básico",
          name: "Tuisty",
          dataPlus: "Semanal",
          data: "3GB",
          usage: "Navegación",
          price: 59,
          llamadas:"Llamadas y SMS Ilimitados a:",
          internet:"Si Comparte Internet",
          socialText:"Redes Sociales Nacionales Ilimitadas",
          socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],
          socialInterText:"Redes Sociales Internacionales Ilimitadas",
          socialMediaInter: [
            "whatsapp",
            "messenger",
            "telegram",
          ],
          duration: "7 días",
          durationPlus: "Ilimitado",
          iftfolio: "1640092"
        },
        {
          id: 7,
          imgPlan: "/img/basicos.png",
          dataPlan:"Tuisty Básico",
          name: "Tuisty",
          dataPlus: "Estándar",
          data: "6GB",
          usage: "Navegación",
          price: 129,
          llamadas:"Llamadas y SMS Ilimitados a:",
          internet:"Si Comparte Internet",
          socialText:"Redes Sociales Nacionales Ilimitadas",
          socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],
          socialInterText:"Redes Sociales Internacionales Ilimitadas",
          socialMediaInter: [
            "whatsapp",
            "messenger",
            "telegram",
          ],
          duration: "15 días",
          durationPlus: "Ilimitado",
          iftfolio: "1640110"
        },
        {
          id: 8,
          imgPlan: "/img/basicos.png",
          dataPlan:"Tuisty Básico",
          name: "Tuisty",
          dataPlus: "Escencial",
          data: "20GB",
          usage: "Navegación",
          price: 149,
          llamadas:"Llamadas y SMS Ilimitados a:",
          internet:"No Comparte Internet",
          socialText:"Redes Sociales Nacionales Ilimitadas",
          socialMedia: [
            "whatsapp",
            "facebook",
            "messenger",
            "twitter",
            "instagram",
            "snapchat",
            "telegram",
          ],
          socialInterText:"Redes Sociales Internacionales Ilimitadas",
          socialMediaInter: [
            "whatsapp",
            "messenger",
            "telegram",
          ],
          duration: "30 días",
          durationPlus: "Ilimitado",
          iftfolio: "1640123"
        },
      ],
    },
    planesTuistyPage: {
        plans: [
            {
              id: 9,
              dataPlan:"Tuisty Mensual",
              imgPlan: "/img/mensuales.png",
              name: "Tuisty",
              dataPlus: "3GB",
              data: "3GB",
              usage: "Navegación",
              price: 129,
              llamadas:"Llamadas y SMS Ilimitados a:",
              internet:"Si Comparte Internet",
              socialText:"Redes Sociales Nacionales Ilimitadas",
              socialMedia: [
                "whatsapp",
                "facebook",
                "messenger",
                "twitter",
                "instagram",
                "snapchat",
                "telegram",
              ],
              socialInterText:"Redes Sociales Internacionales Ilimitadas",
              socialMediaInter: [
                "whatsapp",
                "messenger",
                "telegram",
              ],
              duration: "30 días",
              durationPlus: "Ilimitado",
              iftfolio: "1644012"
            },
            {
              id: 10,
              dataPlan:"Tuisty Mensual",
              imgPlan: "/img/mensuales.png",
              name: "Tuisty",
              dataPlus: "5GB",
              data: "5GB",
              usage: "Navegación",
              price: 149,
              llamadas:"Llamadas y SMS Ilimitados a:",
              internet:"Si Comparte Internet",
              socialText:"Redes Sociales Nacionales Ilimitadas",
              socialMedia: [
                "whatsapp",
                "facebook",
                "messenger",
                "twitter",
                "instagram",
                "snapchat",
                "telegram",
              ],
              socialInterText:"Redes Sociales Internacionales Ilimitadas",
              socialMediaInter: [
                "whatsapp",
                "messenger",
                "telegram",
              ],
              duration: "30 días",
              durationPlus: "Ilimitado",
              iftfolio: "1644035"
            },
            {
              id: 11,
              dataPlan:"Tuisty Mensual",
              imgPlan: "/img/mensuales.png",
              name: "Tuisty",
              dataPlus: "Prime",
              data: "15GB",
              usage: "Navegación",
              price: 229,
              llamadas:"Llamadas y SMS Ilimitados a:",
              internet:"Si Comparte Internet",
              socialText:"Redes Sociales Nacionales Ilimitadas",
              socialMedia: [
                "whatsapp",
                "facebook",
                "messenger",
                "twitter",
                "instagram",
                "snapchat",
                "telegram",
              ],
              socialInterText:"Redes Sociales Internacionales Ilimitadas",
              socialMediaInter: [
                "whatsapp",
                "messenger",
                "telegram",
              ],
              duration: "30 días",
              durationPlus: "Ilimitado",
              iftfolio: "1644057"
              },
              {
                id: 12,
                dataPlan:"Tuisty Mensual",
                imgPlan: "/img/mensuales.png",
                name: "Tuisty",
                dataPlus: "40GB",
                data: "40GB",
                usage: "Navegación",
                price: 279,
                llamadas:"Llamadas y SMS Ilimitados a:",
                internet:"No Comparte Internet",
                socialText:"Redes Sociales Nacionales Ilimitadas",
                socialMedia: [
                  "whatsapp",
                  "facebook",
                  "messenger",
                  "twitter",
                  "instagram",
                  "snapchat",
                  "telegram",
                ],
                socialInterText:"Redes Sociales Internacionales Ilimitadas",
                socialMediaInter: [
                  "whatsapp",
                  "messenger",
                  "telegram",
                ],
                duration: "30 días",
                durationPlus: "Ilimitado",
                iftfolio: "1644078"
              },
              {
                id: 13,
                dataPlan:"Tuisty Mensual",
                imgPlan: "/img/mensuales.png",
                name: "Tuisty",
                dataPlus: "40GB",
                data: "40GB",
                usage: "Navegación",
                price: 349,
                llamadas:"Llamadas y SMS Ilimitados a:",
                internet:"Si Comparte Internet",
                socialText:"Redes Sociales Nacionales Ilimitadas",
                socialMedia: [
                  "whatsapp",
                  "facebook",
                  "messenger",
                  "twitter",
                  "instagram",
                  "snapchat",
                  "telegram",
                ],
                socialInterText:"Redes Sociales Internacionales Ilimitadas",
                socialMediaInter: [
                  "whatsapp",
                  "messenger",
                  "telegram",
                ],
                duration: "30 días",
                durationPlus: "Comparte",
                iftfolio: "1644133"
              },
              {
                id: 14,
                dataPlan:"Tuisty Mensual",
                imgPlan: "/img/mensuales.png",
                name: "Tuisty",
                dataPlus: "100GB",
                data: "100GB",
                usage: "Navegación",
                price: 549,
                llamadas:"Llamadas y SMS Ilimitados a:",
                internet:"Si Comparte Internet",
                socialText:"Redes Sociales Nacionales Ilimitadas",
                socialMedia: [
                  "whatsapp",
                  "facebook",
                  "messenger",
                  "twitter",
                  "instagram",
                  "snapchat",
                  "telegram",
                ],
                socialInterText:"Redes Sociales Internacionales Ilimitadas",
                socialMediaInter: [
                  "whatsapp",
                  "messenger",
                  "telegram",
                ],
                duration: "30 días",
                durationPlus: "Comparte",
                iftfolio: "1644158"
              },
          ],
    },
    planesTrimestralesPage: {
      plans: [
          {
            id: 15,
            dataPlan:"Tuisty Trimestral",
            imgPlan: "/img/trimestrales.png",
            name: "Tuisty",
            dataPlus: "3GB",
            data: "3GB",
            usage: "Navegación",
            price: 334,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "90 días",
            durationPlus: "Trimestral",
            ilimitado:"ilimitado",
            iftfolio: "1644195"
          },
          {
            id: 16,
            dataPlan:"Tuisty Trimestral",
            imgPlan: "/img/trimestrales.png",
            name: "Tuisty",
            dataPlus: "5GB",
            data: "5GB",
            usage: "Navegación",
            price: 399,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "90 días",
            ilimitado:"ilimitado",
            durationPlus: "Trimestral",
            iftfolio: "1644400"
          },
          {
            id: 17,
            dataPlan:"Tuisty Trimestral",
            imgPlan: "/img/trimestrales.png",
            name: "Tuisty",
            dataPlus: "15GB",
            data: "15GB",
            usage: "Navegación",
            price: 649,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "90 días",
            ilimitado:"ilimitado",
            durationPlus: "Trimestral",
            iftfolio: "1644238"
          },
          {
            id: 18,
            dataPlan:"Tuisty Trimestral",
            name: "Tuisty",
            imgPlan: "/img/trimestrales.png",
            dataPlus: "40GB",
            data: "40GB",
            usage: "Navegación",
            price: 749,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"No Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "90 días",
            ilimitado:"ilimitado",
            durationPlus: "Trimestral",
            iftfolio: "1644316"
          },
        ],
    },
    planesSemestralesPage: {
      plans: [
          {
            id: 19,
            dataPlan:"Tuisty Semestral",
            imgPlan: "/img/semestrales.png",
            name: "Tuisty",
            dataPlus: "3GB",
            data: "3GB",
            usage: "Navegación",
            price: 669,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "180 días",
            ilimitado:"ilimitado",
            durationPlus: "Semestral",
            iftfolio: "1644358"
          },
          {
            id: 20,
            dataPlan:"Tuisty Semestral",
            imgPlan: "/img/semestrales.png",
            name: "Tuisty",
            data: "5GB",
            dataPlus:"5GB",
            usage: "Navegación",
            price: 779,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "180 días",
            ilimitado: "ilimitado",
            durationPlus: "Semestral",
            iftfolio: "1346947"
          },
          {
            id: 21,
            dataPlan:"Plan Semestral",
            imgPlan: "/img/semestrales.png",
            name: "Tuisty",
            data: "15GB",
            dataPlus: "15GB",
            usage: "Navegación",
            price: 1299,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "180 días",
            ilimitado: "ilimitado",
            durationPlus: "Semestral",
            iftfolio: "1644431"
          },
          {
            id: 22,
            dataPlan:"Tuisty Semestral",
            imgPlan: "/img/semestrales.png",
            name: "Tuisty",
            data: "40GB",
            dataPlus: "40GB",
            usage: "Navegación",
            price: 1449,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "180 días",
            ilimitado: "ilimitado",
            durationPlus: "Semestral",
            iftfolio: "1346949"
          },
        ],
    },
    planesAnualesPage: {
      plans: [
          {
            id: 23,
            dataPlan:"Tuisty Anual",
            imgPlan: "/img/anuales.png",
            name: "Tuisty",
            data: "3GB",
            dataPlus: "3GB",
            usage: "Navegación",
            price: 1339,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "360 días",
            ilimitado: "ilimitado",
            durationPlus: "Anual",
            iftfolio: "1644489"
          },
          {
            id:24,
            dataPlan:"Tuisty Anual",
            imgPlan: "/img/anuales.png",
            name: "Tuisty",
            data: "5GB",
            dataPlus: "5GB",
            usage: "Navegación",
            price: 1599,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "360 días",
            ilimitado: "ilimitado",
            durationPlus: "Anual",
            iftfolio: "1644509"
          },
          {
            id: 25,
            dataPlan:"Tuisty Anual",
            imgPlan: "/img/anuales.png",
            name: "Tuisty",
            data: "15GB",
            dataPlus: "15GB",
            usage: "Navegación",
            price: 2199,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "360 días",
            ilimitado: "ilimitado",
            durationPlus: "Anual",
            iftfolio: "1644528"
          },
          {
            id: 26,
            dataPlan:"Tuisty Anual",
            imgPlan: "/img/anuales.png",
            name: "Tuisty",
            data: "40GB",
            dataPlus: "40GB",
            usage: "Navegación",
            price: 2669,
            llamadas:"Llamadas y SMS Ilimitados a:",
            internet:"Si Comparte Internet",
            socialText:"Redes Sociales Nacionales Ilimitadas",
            socialMedia: [
              "whatsapp",
              "facebook",
              "messenger",
              "twitter",
              "instagram",
              "snapchat",
              "telegram",
            ],
            socialInterText:"Redes Sociales Internacionales Ilimitadas",
            socialMediaInter: [
              "whatsapp",
              "messenger",
              "telegram",
            ],
            duration: "360 días",
            durationPlus: "Anual",
            iftfolio: "1644548"
          },
        ],
      },
  };
